@startuml Game_Board_ex
() start
() end
() node_1
() node_2
() node_3
() node_4
() node_5
() node_6
() node_7
() node_8
() node_9

start .. node_1
start .. node_2
node_1 .. node_3
node_2 .. node_4
node_2 .. node_5
node_3 .. node_6
node_4 .. node_6
node_5 .. node_7
node_6 .. node_8
node_6 .. node_9
node_7 .. node_9
node_8 .. end
node_9 .. end
@enduml